# -*- coding: utf-8 -*-
"""Lista3-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aN4ra-r4ua8lgtZtpJUjfOT3RPGzIK3p
"""

import pandas as pd
import numpy as np
import re
from prettytable import PrettyTable

#import csv
df= pd.read_csv("/content/drive/MyDrive/python/basefinal2.csv",names=['data'])

#visualizando os dados 

df

#Expresões Regulares

df['funcionarios'] = df['data'].str.extract('([A-Z].*)', expand = True)
df['salario'] = df['data'].str.extract('(\d\d\d\d\d.\d\d)', expand = True)
df['periodo'] = df['data'].str.extract('(....-..-..)', expand = True)
df['Ano']=df['data'].str.extract(r'(\d{4})',expand=False)

df

#exclusão tabela
df.loc[:,~df.columns.str.contains('^data', case=False)]